### ISSUE TITLE
where is the code to implement the memory network

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [VisionLearningGroup/Ask_Attend_and_Answer#4]
Thanks for your sharing !
Could you please tell me that where is the code to implement the memory network?
Thanks for your help and nice work!

**Comment by huijuan88** [comment]
The network architecture is defined in mmnetwork.prototxt. The corresponding layer implementation is in caffe source code.


On Dec 19, 2016, at 07:36, liu666666 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your sharing !
Could you please tell me that where is the code to implement the memory network?
Thanks for your help and nice work!

**Comment by 3DMM-ICME2023** [comment]
Thanks for your reply!
I am afraid that I did not make myself understood.I mean did you only add a new layer (word_sum_layer )to implement the memory network? Could you please give me more details about where is the code you changed mainly for memory network? Which parameter or what code control the second hop start in your code and where is the code to train the Watt and Wa and We in the overview of your paper?
Thank you again for your kind help!

**Comment by huijuan88** [comment]
WordSum and MatrixProd are the newly implemented layers for memory network. The second hop starts roughly from the layer named "eltwise". The layers "embedding_A" and "embedding_C" learn the Wa and We for the first hop. The layers "embedding_C" and "embedding_C2" learn the Wa and We for the second hop. The Wa in the second hop shares weights with We in the first hop, so they both use the same layer "embedding_C".  The layers "weight_g" and "weight2" got the attention weights for the first and second hops.
